OEL-2504: Add an optional title, description and image on the listing page
openeuropa/oe_content_extra pull request #19
Opened 2024-02-22 17:54 UTC by AaronGilMartinez

2024-03-05 10:31 UTC, drishu requested changes

2024-03-05 10:31 UTC, drishu commented on composer.json
> +            "Drupal\\Tests\\oe_content_extra_project\\": "./modules/oe_content_extra_project/tests/src/",
like it was previousley it did not work?  We can surly add another test file next to the old one

2024-03-06 12:49 UTC, AaronGilMartinez commented on composer.json
> +            "Drupal\\Tests\\oe_content_extra_project\\": "./modules/oe_content_extra_project/tests/src/",
Yes, I wasn't sure about grouping all tests in the parent or spliting in the submodules.
What made the difference was the oe_content_extra_list_pages_test test module, didn't want to mix a specific module to test list pages with other tests. 
I can move all things to the parent, but I want to know what do you think first.

2024-03-06 14:39 UTC, AaronGilMartinez commented on composer.json
> +            "Drupal\\Tests\\oe_content_extra_project\\": "./modules/oe_content_extra_project/tests/src/",
Changed images from drone too.

2024-03-07 10:32 UTC, drishu requested changes

2024-03-07 10:32 UTC, drishu commented on composer.json
> +            "Drupal\\Tests\\oe_content_extra_project\\": "./modules/oe_content_extra_project/tests/src/",
ok, you can go with putting the tests in modules, its ok, but there is no need for this change, all you need is the phpunit.xml.dist change

2024-04-22 08:48 UTC, closed without merging